GEMINI_API_KEYS = [
    "AIzaSyC_hYH1Szyj7x0kHE9LQb0UjkUZav7Rx68",
    "AIzaSyDQfd-kg-tpbVzz9XpgYLgVKGdDfnKa5RA",
    "AIzaSyAWKAviyBGDMc0JB61ntPb4QGeTt0rrDYQ",
    "AIzaSyC_zIAxNHLh656k9NHfyYdQ3QQVdzn_45I",
    "AIzaSyAW-IT_x2pG3062zdjpHE0PGbOWmvoL6Lc",
    "AIzaSyArmfdsA4Xp7ogK7p-l8HOn_kWxT-pZlqs",
    "AIzaSyDJ2ZuYEn0MwKGkDy6LzDyrZGaxoAgqLuI",
    "AIzaSyAlfOcC-yO-lnqGmh2AvEcQYKryM9xdmP8",
    "AIzaSyCg5cbnI_2VXFTiJk5_DIWTDFv8I-565RA",
    "AIzaSyA56eTBQA3vfc0vSOS7jyXI9Op__6y8m4A",
    "AIzaSyBP-NWwmud_oVn-FF9HhSG6xMiZq8XCIVA",
    "AIzaSyBbOkt9zClZDwuGyYVyBabDV6qtcsOzJQM"
]